# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Veggie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Veggie
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTImage',
  'RCTWebSocket'
  ]
  
  # Pods for BookMySmile
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'
  
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'


end
